<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary  animated pulse">
            <div class="panel-heading">
                <h3 class="panel-title">Информация</h3>
            </div>
            <div class="panel-body">
                <div class="text-center">
                    <i class="material-icons lk-profile-icon">
                        <?php
                        switch ($this->lkParams['user']->getType())
                        {
                            case 0:
                                echo 'settings';
                                break;
                            case 1:
                                echo 'account_circle';
                                break;
                            default:
                                echo 'account_circle';
                                break;
                        }
                        ?>
                    </i>
                    <p class="lk-username"><?php echo $this->lkParams['user']->getLogin();?></p>
                    <p class="lk-account-type"><?php echo Engine\Module::APPLICATION_CONFIG['userType'][$this->lkParams['user']->getType()];?></p>
                </div>
                <br>
            </div>
        </div>
    </div>
    <?php
    $this->navigation_helper($this->currentRoute(), 'breadcrumbs');
    $this->navigation_helper($this->currentRoute(), 'navigationMenu');
    ?>
</div>