<div class="col-centered col-lg-5 margin-top-20-important min-width-450px">
    <div class="bs-docs-selection animated fadeIn" style="text-align: center;" name="ChangePasswordCard">
        <div class="well" style="word-wrap: break-word;">
            <?
                $form = $this->form;
                echo  $this->form()->openTag($form);
                echo  '<h3>'.$this->navigation('lk_navigation')->findOneBy('active', 1).'</h3>';

                echo  '<fieldset>';
                foreach ($form as $element)
                {
                    echo '<div class="form-group">';
                    $attributes = $element->getAttributes();

                    if($element->getLabel())
                    {
                        $element->setLabelAttributes(array('class' => 'col-lg-4 control-label'));

                    }

                    if (isset($attributes['type']) && $attributes['type'] == 'password')
                    {
                        echo $this->formLabel($element);
                        echo  '<div class = "col-lg-7">';
                        echo  $this->formInput($element);
                        echo  '</div>';
                    }
                    elseif (isset($attributes['type']) && $attributes['type'] == 'submit')
                    {
                        echo  '<div class = "col-lg-10" style="width: 100%">';
                        echo  $this->formRow($element);
                        echo  '</div>';
                    }
                    else
                    {
                        echo  '<div class = "col-lg-10">';
                        echo $this->formRow($element);
                        echo  '</div>';
                    }
                    echo '</div>';
                }
                echo '</fieldset>';
                echo  $this->form()->closeTag();

                ?>
        </div>
    </div>
    <div class="bs-docs-selection animated fadeIn hidden" name="ChangePasswordSuccessCard" style="text-align: center;">
        <div class="well"><br><br><br><br><br><br>
            <h3>Вы успешно сменили пароль</h3><br><br><br><br><br><br>
            <a class="btn btn-primary"  href="<?= $this->url('lk/edit') ?>"><? echo 'Вернуться'; ?></a>
        </div>
    </div>
</div>
<script>
    $('#PasswordForm').submit(function() {
        $('.alert').remove();
        $.ajax({
            type: 'POST',
            url: '<?= $this->url('api/user', ['action' => 'changePassword']) ?>',
            data: $('#PasswordForm').serialize(),
            success: function(data) {
                var arr = $.map(data, function(el) {
                    return el
                });
                if (arr[0] == 'success') {
                    $('div[name=ChangePasswordCard]').remove();
                    $('div[name=ChangePasswordSuccessCard]').removeClass('hidden');
                    setTimeout(function() { location.href = "<?= $this->url('lk/edit') ?>"; }, 5000)
                }
                if (arr[0] == 'error') {
                    $(  '<div class="alert alert-dismissable alert-danger">' +
                        '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×' +
                        '</button>' +
                        '<ul></ul></div>').insertAfter("form > h3");
                    for (var i = 1; i < arr.length; i++) {
                        $('<li>' + arr[i] + '</li>').insertAfter("form > .alert > ul");
                    }
                }
            },
            error: function(xhr, ajaxOptions, thrownError) {
                $(
                    '<div class="alert alert-dismissable alert-danger">' +
                    '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×' +
                    '</button>' +
                    '<ul><li>' + xhr.status + ' ' + thrownError + '</li></ul></div>').insertAfter("form > h3");
            }
        });
        return false;
    });
</script>
