<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle(Engine\Module::APPLICATION_NAME)->setSeparator(' - ')->setAutoEscape(false)->append($this->navigation_helper($this->currentRoute(), 'headTitle')) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' =>  '/public/img/favicon.ico'])
        ->prependStylesheet($this->basePath('public/css/style.css'))
        ->prependStylesheet($this->basePath('public/css/animate.css'))
        ->prependStylesheet($this->basePath('public/css/ripples.min.css'))
        ->prependStylesheet($this->basePath('public/css/bootstrap-material-design.min.css'))
        //->prependStylesheet($this->basePath('public/css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('public/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('public/css/material-icons.css'))
        ->prependStylesheet('//fonts.googleapis.com/icon?family=Material+Icons')
        ->prependStylesheet('//fonts.googleapis.com/css?family=Roboto:300,400,500,700')
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('public/js/ripples.min.js'))
        ->prependFile($this->basePath('public/js/material.min.js'))
        ->prependFile($this->basePath('public/js/bootstrap.min.js'))
        ->prependFile($this->basePath('public/js/jquery-1.10.2.min.js'))
    ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= Engine\Module::APPLICATION_LOGO_URL ?>" height="28" alt="<?= Engine\Module::APPLICATION_NAME?>"/>&nbsp;<?= Engine\Module::APPLICATION_NAME?>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="javascript:void(0)" data-target="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <? if (empty($this->user)) echo 'Меню'; else
                        {
                            echo $this->user->getLogin();
                            echo $this->user->getType() < 2 ? ' (' . Engine\Module::APPLICATION_CONFIG['userType'][$this->user->getType()]. ')' : '';
                        } ?>
                        <b class="caret"></b><div class="ripple-container"></div></a>
                    <ul class="dropdown-menu">
                        <?
                        if (empty($this->user))
                        {
                            echo '<li><a href="/auth/login/">Войти</a></li>';
                            echo '<li><a href="/auth/registration/">Регистрация</a></li>';
                        }
                        else
                        {
                            echo '<li><a href="/lk/">Личный кабинет</a></li>';

                            if ($this->user->getType() == 0 || $this->user->getType() == 1)
                                echo '<li><a href="/admin/">Панель управления</a></li>';
                            echo '<li class="divider"></li>';
                            echo '<li><a href="/auth/logout/">Выйти</a></li>';
                        }
                        ?>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->navigation_helper($this->currentRoute(), 'pageTitle');?>
    <?= $this->navigation_helper($this->currentRoute(), 'breadcrumbs');?>
    <?= $this->content ?>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
